export const allResources = [
    {
      id: 1,
      name: 'Hopelink',
      category: 'Food & Nutrition',
      description: 'Food bank services, energy assistance, and emergency support for families in Redmond. Open to all community members in need.',
      address: '15910 NE 85th St, Redmond, WA 98052',
      lat: 47.6785,
      lng: -122.1230,
      phone: '(555) 123-4567',
      website: 'hopelink.org',
    },
    {
      id: 2,
      name: 'Redmond Community Resource Center',
      category: 'Health & Wellness',
      description: 'Located at the Redmond Library, offering mental health assessments, substance use support, housing assistance, and employment services.',
      address: '15990 NE 85th St, Redmond, WA 98052',
      lat: 47.6790,
      lng: -122.1225,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 3,
      name: 'Redmond Library',
      category: 'Education',
      description: 'Free library services, computer access, educational programs, and community meeting spaces for all ages.',
      address: '15990 NE 85th St, Redmond, WA 98052',
      lat: 47.6790,
      lng: -122.1225,
      phone: '(555) 234-5678',
      website: 'kcls.org',
    },
    {
      id: 4,
      name: 'YWCA Family Village Redmond',
      category: 'Housing',
      description: 'Permanent supportive housing with programs including Working Wardrobe, employment training, and family support services.',
      address: '16650 NE 80th St, Redmond, WA 98052',
      lat: 47.6735,
      lng: -122.1228,
      phone: '(555) 345-6789',
      website: 'ywcaworks.org',
    },
    {
      id: 5,
      name: 'OneRedmond',
      category: 'Employment',
      description: 'Local chamber of commerce supporting businesses with resources, advocacy, networking events, and community development initiatives.',
      address: '16300 NE 80th St, Redmond, WA 98052',
      lat: 47.6720,
      lng: -122.1220,
      phone: '(555) 456-7890',
      website: 'oneredmond.org',
    },
    {
      id: 6,
      name: 'City of Redmond Senior Center',
      category: 'Senior Services',
      description: 'Health and wellness programs, social activities, fitness classes, and support services for Redmond seniors.',
      address: '8703 160th Ave NE, Redmond, WA 98052',
      lat: 47.6745,
      lng: -122.1250,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 7,
      name: 'King County Bar Association Pro Bono Services',
      category: 'Legal',
      description: 'Free legal assistance and consultation for low-income residents, including family law, housing, and consumer protection.',
      address: '1200 5th Ave, Seattle, WA 98101',
      lat: 47.6107,
      lng: -122.3365,
      phone: '(555) 567-8901',
      website: 'kcba.org',
    },
    {
      id: 8,
      name: 'City of Redmond Human Services',
      category: 'Family Services',
      description: 'Funding and support for local nonprofits offering child care, counseling, employment assistance, and medical care for families.',
      address: '15670 NE 85th St, Redmond, WA 98052',
      lat: 47.6803,
      lng: -122.1237,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 9,
      name: 'Indian American Community Services',
      category: 'Community Services',
      description: 'Inter-generational programming, community support, and resources for small businesses serving the Indian American community in Redmond.',
      address: '15220 NE 40th St, Redmond, WA 98052',
      lat: 47.6725,
      lng: -122.1348,
      phone: '(555) 678-9012',
      website: 'iacswa.org',
    },
    {
      id: 10,
      name: 'Together Center',
      category: 'Community Services',
      description: 'A centralized nonprofit hub in Redmond where residents can access food assistance, housing support, healthcare navigation, and social services in one location.',
      address: '16305 NE 87th St, Redmond, WA 98052',
      lat: 47.6809,
      lng: -122.1213,
      phone: '(425) 242-5320',
      website: 'togethercenter.org',
    },
    {
      id: 11,
      name: 'Redmond Teen Center @ Old Fire House',
      category: 'Youth Services',
      description: 'Free drop-in center for middle and high school students offering games, tutoring, leadership opportunities, and a safe place to socialize.',
      address: '16510 NE 79th St, Redmond, WA 98052',
      lat: 47.6729,
      lng: -122.1219,
      phone: '(425) 556-2300',
      website: 'redmond.gov',
    },
    {
      id: 12,
      name: 'Redmond Parks and Recreation',
      category: 'Recreation',
      description: 'City department managing parks, trails, recreation centers, sports programs, and community activities for residents of all ages.',
      address: '15670 NE 85th St, Redmond, WA 98052',
      lat: 47.6803,
      lng: -122.1237,
      phone: '(425) 556-2300',
      website: 'redmond.gov',
    },
    {
      id: 13,
      name: 'Marymoor Park',
      category: 'Recreation',
      description: 'Large regional park in Redmond offering trails, sports fields, dog parks, concerts, and community events throughout the year.',
      address: '6046 W Lake Sammamish Pkwy NE, Redmond, WA 98052',
      lat: 47.6537,
      lng: -122.1095,
      phone: '(206) 477-7275',
      website: 'kingcounty.gov',
    },
    {
      id: 14,
      name: 'VALA Art Center',
      category: 'Arts & Culture',
      description: 'Nonprofit art center in downtown Redmond offering exhibitions, art classes, workshops, and community cultural events.',
      address: '7979 Gilman St, Redmond, WA 98052',
      lat: 47.6733,
      lng: -122.1216,
      phone: '(425) 835-7666',
      website: 'valaart.org',
    },
    {
      id: 15,
      name: 'Redmond Center for the Performing Arts',
      category: 'Arts & Culture',
      description: 'Public performing arts venue hosting concerts, theater productions, cultural performances, and community events.',
      address: '17272 NE 104th St, Redmond, WA 98052',
      lat: 47.6946,
      lng: -122.1209,
      phone: '(425) 556-2300',
      website: 'redmond.gov',
    },
    {
      id: 16,
      name: 'WorkSource Redmond',
      category: 'Employment',
      description: 'Employment and career resource center offering job search help, resume support, career counseling, and training referrals.',
      address: '7225 170th Ave NE, Redmond, WA 98052',
      lat: 47.6697,
      lng: -122.1143,
      phone: '(425) 861-3770',
      website: 'worksourcewa.com',
    },
    {
      id: 17,
      name: 'Redmond Saturday Market',
      category: 'Community Events',
      description: 'Weekly outdoor market in downtown Redmond featuring local farmers, food vendors, artisans, and live entertainment.',
      address: 'Downtown Park, 16101 NE Redmond Way, Redmond, WA 98052',
      lat: 47.6730,
      lng: -122.1210,
      phone: '(425) 591-0252',
      website: 'redmondsaturdaymarket.org',
    },
    {
      id: 18,
      name: 'Woodinville Community Resource Center',
      category: 'Community Services',
      description: 'Provides access to food assistance, family services, housing support, and referrals for residents in the greater Redmond area.',
      address: '13370 NE 175th St, Woodinville, WA 98072',
      lat: 47.7561,
      lng: -122.1594,
      phone: '(425) 485-6541',
      website: 'woodinvillecrc.org',
    }
  ]
