export const allResources = [
    {
      id: 1,
      name: 'Hopelink',
      category: 'Food & Nutrition',
      description: 'Food bank services, energy assistance, and emergency support for families in Redmond. Open to all community members in need.',
      address: '15910 NE 85th St, Redmond, WA 98052',
      lat: 47.6785,
      lng: -122.1230,
      phone: '(555) 123-4567',
      website: 'hopelink.org',
    },
    {
      id: 2,
      name: 'Redmond Community Resource Center',
      category: 'Health & Wellness',
      description: 'Located at the Redmond Library, offering mental health assessments, substance use support, housing assistance, and employment services.',
      address: '15990 NE 85th St, Redmond, WA 98052',
      lat: 47.6790,
      lng: -122.1225,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 3,
      name: 'Redmond Library',
      category: 'Education',
      description: 'Free library services, computer access, educational programs, and community meeting spaces for all ages.',
      address: '15990 NE 85th St, Redmond, WA 98052',
      lat: 47.6790,
      lng: -122.1225,
      phone: '(555) 234-5678',
      website: 'kcls.org',
    },
    {
      id: 4,
      name: 'YWCA Family Village Redmond',
      category: 'Housing',
      description: 'Permanent supportive housing with programs including Working Wardrobe, employment training, and family support services.',
      address: '16650 NE 80th St, Redmond, WA 98052',
      lat: 47.6735,
      lng: -122.1228,
      phone: '(555) 345-6789',
      website: 'ywcaworks.org',
    },
    {
      id: 5,
      name: 'OneRedmond',
      category: 'Employment',
      description: 'Local chamber of commerce supporting businesses with resources, advocacy, networking events, and community development initiatives.',
      address: '16300 NE 80th St, Redmond, WA 98052',
      lat: 47.6720,
      lng: -122.1220,
      phone: '(555) 456-7890',
      website: 'oneredmond.org',
    },
    {
      id: 6,
      name: 'City of Redmond Senior Center',
      category: 'Senior Services',
      description: 'Health and wellness programs, social activities, fitness classes, and support services for Redmond seniors.',
      address: '8703 160th Ave NE, Redmond, WA 98052',
      lat: 47.6745,
      lng: -122.1250,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 7,
      name: 'King County Bar Association Pro Bono Services',
      category: 'Legal',
      description: 'Free legal assistance and consultation for low-income residents, including family law, housing, and consumer protection.',
      address: '1200 5th Ave, Seattle, WA 98101',
      lat: 47.6107,
      lng: -122.3365,
      phone: '(555) 567-8901',
      website: 'kcba.org',
    },
    {
      id: 8,
      name: 'City of Redmond Human Services',
      category: 'Family Services',
      description: 'Funding and support for local nonprofits offering child care, counseling, employment assistance, and medical care for families.',
      address: '15670 NE 85th St, Redmond, WA 98052',
      lat: 47.6803,
      lng: -122.1237,
      phone: '(555) 234-5678',
      website: 'redmond.gov',
    },
    {
      id: 9,
      name: 'Indian American Community Services',
      category: 'Community Services',
      description: 'Inter-generational programming, community support, and resources for small businesses serving the Indian American community in Redmond.',
      address: '15220 NE 40th St, Redmond, WA 98052',
      lat: 47.6725,
      lng: -122.1348,
      phone: '(555) 678-9012',
      website: 'iacswa.org',
    },
  ]